In [1]:
import numpy as np

A = np.random.randint(100,size=(3,4))
print(A)
print(np.sum(A,1,keepdims=True))
print(np.sum(A,0,keepdims=True))
print(A[:2])
print(A[:,2:])

[[59 55  2 93]
 [39 61 93 79]
 [20 57 86 48]]
[[209]
 [272]
 [211]]
[[118 173 181 220]]
[[59 55  2 93]
 [39 61 93 79]]
[[ 2 93]
 [93 79]
 [86 48]]
