In [1]:
import numpy as np

A = np.ones((3,2))
print(A)

B = np.random.randint(1,7,(3,2))
print(B)

print("A+B=\n",A+B)
print("A-B=\n",A-B)
print("A*B=\n",A*B)
print("A/B=\n",A/B)

print("A . B = \n",A@B.T)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[6 4]
 [5 4]
 [1 3]]
A+B=
 [[7. 5.]
 [6. 5.]
 [2. 4.]]
A-B=
 [[-5. -3.]
 [-4. -3.]
 [ 0. -2.]]
A*B=
 [[6. 4.]
 [5. 4.]
 [1. 3.]]
A/B=
 [[0.16666667 0.25      ]
 [0.2        0.25      ]
 [1.         0.33333333]]
A . B = 
 [[10.  9.  4.]
 [10.  9.  4.]
 [10.  9.  4.]]
