In [1]:
import numpy as np

A = np.random.rand(10)
print(A)
A = A.reshape(5,2)
print(A)

B = np.array([[1,2],[3,4]])
print(B)
print(B[:,[1,0]])

[0.69160168 0.18279413 0.20544053 0.09750469 0.40664334 0.98730527
 0.77534365 0.95501669 0.44302962 0.78026876]
[[0.69160168 0.18279413]
 [0.20544053 0.09750469]
 [0.40664334 0.98730527]
 [0.77534365 0.95501669]
 [0.44302962 0.78026876]]
[[1 2]
 [3 4]]
[[2 1]
 [4 3]]
